var na=void 0,n=null,oa,xa,Ea;
(function(){function b(c,b,j,g,d,u){if(c&&typeof c=="object")b=c.h,g=c.f,u=c.y,j=c.e,d=c.x,c=c.g;this.g=c==n?1:c;this.h=b||0;this.e=j||0;this.f=g==n?1:g;this.x=(d==n?this.x:d)||0;this.y=(u==n?this.y:u)||0;return this}oa=function(c){function b(){}b.prototype=typeof c=="function"?c.prototype:c;for(var j=new b,g=1,d=arguments.length;g<d;g++){var u=arguments[g];if(typeof u=="function")u=u.prototype;for(var A in u)j[A]=u[A]}if(j.U)b=j.U;b.prototype=j;return b};oa({Ia:function(c){if(c.element)c=c.element;
c.appendChild(this.element);return this},ob:function(){var c=this.element,b=c.parentNode;b&&b.removeChild(c);return this},Qa:function(c,b,j){if(typeof c!="string"){var g=[],d;for(d in c)g.push(this.Qa(d,c[d]));return function(){for(var c=0,b=g.length;c<b;c++)g[c]();return this}}else{var u=b.bind(j||this),A=this.element;return A.addEventListener?(A.addEventListener(c,u,!1),function(){A.removeEventListener(c,u,!1);return this}):(A.attachEvent("on"+c,u),function(){A.detachEvent("on"+c,u);return this})}}});
oa({xb:function(){for(var c=0;c<arguments.length;c++)arguments[c].Ia(this);return this}});xa=oa({U:b,ab:function(){},g:1,h:0,x:0,e:0,f:1,y:0,transform:function(c,b,j,g,d,u){if(c&&typeof c=="object")b=c.h,g=c.f,u=c.y,j=c.e,d=c.x,c=c.g;d||(d=0);u||(u=0);return this.ba(this.g*c+this.e*b,this.h*c+this.f*b,this.g*j+this.e*g,this.h*j+this.f*g,this.g*d+this.e*u+this.x,this.h*d+this.f*u+this.y)},ba:b,translate:function(c,b){return this.transform(1,0,0,1,c,b)},move:function(c,b){this.x+=c||0;this.y+=b||0;
return this},scale:function(c,b){b==n&&(b=c);return this.transform(c,0,0,b,0,0)},rotate:function(c,b,j){if(b==n||j==n)b=(this.left||0)+(this.width||0)/2,j=(this.top||0)+(this.height||0)/2;var g=c*Math.PI/180,c=Math.sin(g),g=Math.cos(g);this.transform(1,0,0,1,b,j);return this.ba(g*this.g-c*this.h,c*this.g+g*this.h,g*this.e-c*this.f,c*this.e+g*this.f,this.x,this.y).transform(1,0,0,1,-b,-j)},moveTo:function(c,b){return this.ba(this.g,this.h,this.e,this.f,c,b)},Ob:function(c,b,j){var g=this.h/this.g>
this.f/this.e?-1:1;if(this.g<0?this.e>=0:this.e<0)g=-g;return this.rotate(c-Math.atan2(g*this.h,g*this.g)*180/Math.PI,b,j)},Na:function(c,b){var j=Math.sqrt(this.g*this.g+this.h*this.h);this.g/=j;this.h/=j;j=Math.sqrt(this.f*this.f+this.e*this.e);this.f/=j;this.e/=j;return this.scale(c,b)},resizeTo:function(c,b){var j=this.width,g=this.height;return!j||!g?this:this.Na(c/j,b/g)},A:function(c,b){return{x:this.g*c+this.e*b+this.x,y:this.h*c+this.f*b+this.y}}})})();
(function(){function b(b,s,c){return function(z,q,h,l,g,r){var j=arguments.length;return this.push(j<4?b:j<6?s:c,z,q,h,l,g,r)}}function c(b,s){return function(c,z,q,h,l){return this.push(b,Math.abs(q||c),Math.abs(h||q||z),0,l?1:0,s,c,z)}}function J(b){return function(s,c){return this.push(b,s,c)}}function j(b,s,c,z,q,h,l,g,r){var o=l-b,v=g-s,d=o*o+v*v,m,a,e,k;a=c-b;e=z-s;k=a*o+e*v;k>d?(a-=o,e-=v):k>0&&d!=0&&(a-=k/d*o,e-=k/d*v);m=a*a+e*e;a=q-b;e=h-s;k=a*o+e*v;k>d?(a-=o,e-=v):k>0&&d!=0&&(a-=k/d*o,e-=
k/d*v);m<0.01&&a*a+e*e<0.01?r(b,s,l,g):(m=(c+q)*0.5,d=(z+h)*0.5,c=(c+b)*0.5,z=(z+s)*0.5,o=(c+m)*0.5,v=(z+d)*0.5,q=(l+q)*0.5,h=(g+h)*0.5,m=(q+m)*0.5,d=(h+d)*0.5,a=(o+m)*0.5,e=(v+d)*0.5,j(b,s,c,z,o,v,a,e,r),j(a,e,m,d,q,h,l,g,r))}function g(b,s,c,z,q,h,l,g,r,d,o){var c=c*Math.PI/180,m=Math.cos(c),j=Math.sin(c);h-=g;l-=r;var c=m*h/2+j*l/2,a=-j*h/2+m*l/2,e=b*b*s*s,k=s*s*c*c,w=b*b*a*a,f=e-w-k;f<0?(f=Math.sqrt(1-f/e),b*=f,s*=f,c=h/2,a=l/2):(f=Math.sqrt(f/(w+k)),z==q&&(f=-f),a=-f*a*b/s,f=f*c*s/b,c=m*a-j*
f+h/2,a=j*a+m*f+l/2);var z=m/b,e=j/b,k=-j/s,w=m/s,f=Math.atan2(k*-c+w*-a,z*-c+e*-a),Fa=Math.atan2(k*(h-c)+w*(l-a),z*(h-c)+e*(l-a));c+=g;a+=r;h+=g;l+=r;if(b==s&&o)o(g,r,h,l,c,a,b,f,Fa,!q);else{z=m*b;e=-j*s;k=j*b;w=m*s;h=Fa-f;h<0&&q?h+=Q:h>0&&!q&&(h-=Q);q=Math.ceil(Math.abs(h/(Q/4)));b=h/q;s=4/3*Math.tan(b/4);h=Math.cos(f);l=Math.sin(f);for(o=0;o<q;o++){m=h-s*l;j=l+s*h;f+=b;var h=Math.cos(f),l=Math.sin(f),Fa=h+s*l,mb=l-s*h;d(g,r,c+z*m+e*j,a+k*m+w*j,c+z*Fa+e*mb,a+k*Fa+w*mb,g=c+z*h+e*l,r=a+k*h+w*l)}}}
function d(c,b,g,z){m=Math.min(m,c,g);H=Math.max(H,c,g);C=Math.min(C,b,z);G=Math.max(G,b,z)}function u(c,b,g,z,q,h,l,o){m=Math.min(m,c,g,q,l);H=Math.max(H,c,g,q,l);C=Math.min(C,b,z,h,o);G=Math.max(G,b,z,h,o)}function A(c,b,g,o,q,h,l,j,r,d){var v=d?r:j,r=d?j:r;r<v&&(r+=Q);j=r>M?q-l:g;g=r>Q+Z||v<Z&&r>Z?q+l:g;q=r>Q+F||v<F&&r>F?h-l:o;o=r>Q+E||v<E&&r>E?h+l:o;m=Math.min(m,c,j,g);H=Math.max(H,c,j,g);C=Math.min(C,b,q,o);G=Math.max(G,b,q,o)}function y(c,b,g,o){var c=g-c,b=o-b,q=Math.sqrt(c*c+b*b);S+=q;if(S>=
O){var h=(S-O)/q,l=c/q,q=b/q;g-=c*h;o-=b*h;fa=new xa(l,q,-q,l,g,o);O=Infinity}}function o(c,b,g,o){c=g-c;b=o-b;S+=Math.sqrt(c*c+b*b)}var t={Cb:2,$b:0,yb:1,Zb:1,eb:6,Pb:4,Kb:4,Xb:2,bb:7},Q=Math.PI*2,m,H,C,G,M=Q/2,E=M/2,F=-E,Z=0,S,O,fa;Ea=oa({U:function(c){if(c instanceof Ea)this.path=Array.prototype.slice.call(c.path),this.l=c.l;else{var b;if(c==n)b=[];else if(c){b=[];for(var g=-1,o=c.match(/[a-df-z]|[\-+]?(?:[\d\.]e[\-+]?|[^\s\-+,a-z])+/ig),q,h,l=0,j=0,d=o.length;j<d;j++){var m=o[j];if(m.match(/^[a-z]/i)){if(h&&
h.length-1<l)throw Error("Missing parameters");q=m;b[++g]=h=[q];q=="m"?q="l":q=="M"&&(q="L");l=t[q.toLowerCase()]}else h.length>l&&(b[++g]=h=[q]),h.push(Number(m))}if(h&&h.length-1<l)throw Error("Missing parameters");}else b=[];this.path=b;this.l={aa:String(c)}}},push:function(){this.l={};this.path.push(Array.prototype.slice.call(arguments));return this},reset:function(){this.l={};this.path=[];return this},move:J("m"),moveTo:J("M"),a:J("l"),lineTo:J("L"),mb:b("t","q","c"),za:b("T","Q","C"),arc:c("a",
1),arcTo:c("A",1),jb:c("a",0),kb:c("A",0),close:function(){return this.push("z")},N:function(c,b,o,m,q){b||(b=function(a,e,b,k,f,h,w,l){j(a,e,b,k,f,h,w,l,c)});for(var h=0,l=0,d=0,r=0,y,v,t,A=this.path,a=0;a<A.length;a++){var e=Array.prototype.slice.call(A[a]);y=e.shift();var k=y.toLowerCase(),w=k==y?h:0,f=k==y?l:0;k!="m"&&k!="z"&&v==n&&(v=h,t=l);switch(k){case "m":m?m(h,l,h=w+e[0],l=f+e[1]):(h=w+e[0],l=f+e[1]);break;case "l":c(h,l,h=w+e[0],l=f+e[1]);break;case "c":d=w+e[2];r=f+e[3];b(h,l,w+e[0],f+
e[1],d,r,h=w+e[4],l=f+e[5]);break;case "s":y=[h*2-d,l*2-r];d=w+e[0];r=f+e[1];b(h,l,y[0],y[1],d,r,h=w+e[2],l=f+e[3]);break;case "q":d=w+e[0];r=f+e[1];b(h,l,(h+d*2)/3,(l+r*2)/3,((h=w+e[2])+d*2)/3,((l=f+e[3])+r*2)/3,h,l);break;case "t":y=[h*2-d,l*2-r];d=y[0];r=y[1];b(h,l,(h+d*2)/3,(l+r*2)/3,((h=w+e[0])+d*2)/3,((l=f+e[1])+r*2)/3,h,l);break;case "a":d=w+e[5];r=f+e[6];!e[0]||!e[1]||d==h&&r==l?c(h,l,d,r):g(e[0],e[1],e[2],e[3],e[4],d,r,h,l,b,o);h=d;l=r;break;case "h":c(h,l,h=w+e[0],l);break;case "v":c(h,
l,h,l=f+e[0]);break;case "z":v!=n&&(q?(q(),m?m(h,l,h=v,l=t):(h=v,l=t)):c(h,l,h=v,l=t),v=n)}k!="s"&&k!="c"&&k!="t"&&k!="q"&&(d=h,r=l)}},Ta:function(){if(this.l.aa==n){for(var c="",b=0,g=this.path.length;b<g;b++)c+=this.path[b].join(" ");this.l.aa=c}return this.l.aa},Ja:function(){if(this.l.ca==n)m=C=Infinity,H=G=-Infinity,this.N(d,u,A),this.l.ca=m==Infinity?{left:0,top:0,right:0,bottom:0,width:0,height:0}:{left:m,top:C,right:H,bottom:G,width:H-m,height:G-C};return this.l.ca},A:function(b){S=0;O=b;
fa=n;this.N(y);return fa},W:function(){S=0;this.N(o);return S}});Ea.prototype.toString=Ea.prototype.Ta})();
(function(){function b(b,c,g){var m=b=="R"?A:b=="X"?d:u;!g&&!m.length&&(g="linear");var j;y>t?j="100%":(j=(y/t*100).toFixed(G),o&&(j=(+j+o).toFixed(6)),j=j.replace(F,"")+"%");b=E+C+"transform: "+(b=="R"?"rotate("+(c*180/Math.PI).toFixed(2).replace(F,"")+"deg)":"translate"+b+"("+c.toFixed(2).replace(F,"")+"px)");g=g?E+C+"animation-timing-function: "+g+";":"";C=="-webkit-"&&m.length<1&&(b+=";\n"+E+b+" translateZ(0px)");m.push(j+" {",b+";",g,"}")}function c(b,c,g,d,o){var s=1/3,j=2/3,m=3*(1-s)*(1-s)*
s,q=3*(1-s)*s*s,h=3*(1-j)*(1-j)*j,l=3*(1-j)*j*j,y=m*l-q*h;b-=s*s*s;c-=s*s*s;g-=j*j*j;j=d-j*j*j;d=(l*b-q*g)/y;q=(l*c-q*j)/y;l=(-h*b+m*g)/y;m=(-h*c+m*j)/y;d<0&&(d=0);q<0&&(q=0);l<0&&(l=0);m<0&&(m=0);d>1&&(d=1);q>1&&(q=1);l>1&&(l=1);m>1&&(m=1);return d==q&&l==m?"linear":"cubic-bezier("+[d.toFixed(o).replace(F,""),q.toFixed(o).replace(F,""),l.toFixed(o).replace(F,""),m.toFixed(o).replace(F,"")]+")"}function J(c,g,j,d){var t=j-c,s=d-g,A=Math.sqrt(t*t+s*s),t=Math.atan2(s/A,t/A);b("X",c,"linear");b("Y",
g,"linear");o=0;H!==na&&H!==t&&(b("R",H),o=M);b("R",t,"linear");y+=A;Q=j;m=d;H=t;o=0}function j(g,d,t,A,u,s,E,z){var q=E-g,h=z-d,l=q*q+h*h,C,r,G,v;r=t-g;G=A-d;v=r*q+G*h;var F=-r*h+G*q;v>l?(r-=q,G-=h):v>0&&l!=0&&(r-=v/l*q,G-=v/l*h);C=r*r+G*G;r=u-g;G=s-d;v=r*q+G*h;var P=-r*h+G*q;v>l?(r-=q,G-=h):v>0&&l!=0&&(r-=v/l*q,G-=v/l*h);C<0.01&&r*r+G*G<0.01?J(g,d,E,z):(v=(t-g)/q,l=(A-d)/h,C=(u-g)/q,r=(s-d)/h,G=Math.sqrt(v*v+l*l)+Math.sqrt((v-C)*(v-C)+(l-r)*(l-r))+Math.sqrt((1-C)*(1-C)+(1-r)*(1-r)),q==0||h==0||
v<0||l<0||C<0.1||r<0.1||v>0.9||l>0.9||C>1||r>1||G>1.75||!(F<0&&P<0||F>0&&P>0)?(P=(t+u)*0.5,F=(A+s)*0.5,v=(t+g)*0.5,h=(A+d)*0.5,l=(v+P)*0.5,q=(h+F)*0.5,u=(E+u)*0.5,s=(z+s)*0.5,A=(u+P)*0.5,t=(s+F)*0.5,F=(l+A)*0.5,P=(q+t)*0.5,j(g,d,v,h,l,q,F,P),j(F,P,A,t,u,s,E,z)):(A=(new Ea).moveTo(g,d).za(t,A,u,s,E,z),s=A.W(),v=1/3,u=2/3,P=A.A(0),F=A.A(s*v),l=A.A(s*u),C=A.A(s),A=(F.x-g)/q,t=(F.y-d)/h,q=(l.x-g)/q,h=(l.y-d)/h,P=Math.atan2(-P.e,P.f),C=Math.atan2(-C.e,C.f),r=C-P,F=(Math.atan2(-F.e,F.f)-P)/r,l=(Math.atan2(-l.e,
l.f)-P)/r,r=Math.ceil(-Math.log(1/s)/Math.log(10)),r<0&&(r=0),b("X",g,c(v,A,u,q,r)),b("Y",d,c(v,t,u,h,r)),o=0,H!==na&&H!==P&&(b("R",H),o=M),b("R",P,c(v,F,u,l,r)),y+=s,o=0,Q=E,m=z,H=C))}function g(){Q!==na&&(b("X",Q),b("Y",m),o=M,Q=m=na)}var d,u,A,y,o,t,Q,m,H,C,G,M=1.0E-4,E="  ",F=/^0+(?=\.\d*[^0])|\.?0+$/g;Ea.prototype.Sa=function(c){C=c||"";y=0;t=this.W();Q=m=H=na;d=[];u=[];A=[];G=Math.ceil(-Math.log(1/t*100)/Math.log(10));G<0&&(G=0);this.N(J,j,n,g);Q!==na&&(b("X",Q),b("Y",m));H!==na&&b("R",H);c=
{x:E+d.join("\n"+E),y:E+u.join("\n"+E),Ka:E+A.join("\n"+E)};d=u=A=n;return c}})();
function La(b){var c=this.X=document.createElement("div"),J=this.top=document.createElement("div"),j=this.left=document.createElement("div"),g=this.bottom=document.createElement("div"),d=this.right=document.createElement("div");c.className="fade-scroller";J.className="fade-top";j.className="fade-left";g.className="fade-bottom";d.className="fade-right";for(b.style.overflow="hidden";b.firstChild;)c.appendChild(b.firstChild);b.appendChild(J);b.appendChild(j);b.appendChild(g);b.appendChild(d);b.appendChild(c);
var u=this;c.addEventListener("scroll",function(){u.update()},!1);this.update();b.scrollTop=b.scrollLeft=0}La.prototype.Ca=51;La.prototype.Ba=0.3;La.prototype.update=function(){var b=this.X,c=b.scrollLeft,J=b.scrollTop,j=b.scrollWidth-b.offsetWidth-c,b=b.scrollHeight-b.offsetHeight-J,g=this.Ca,d=this.Ba;this.top.style.top=(J*d>g?0:J*d-g)+"px";this.left.style.left=(c*d>g?0:c*d-g)+"px";this.bottom.style.bottom=(b*d>g?0:b*d-g)+"px";this.right.style.right=(j*d>g?0:j*d-g)+"px"};
function lb(b){var c=this.selected={"-webkit-":!0,"-moz-":!0,"-ms-":!0,"-o-":!0,"":!0},J=b.lastChild,j;for(j in c){var g=document.createElement("a");g.appendChild(document.createElement("span"));var d=document.createElement("div");d.appendChild(document.createTextNode(j||"w3c"));g.appendChild(d);g.className=j.replace(/\-/g,"");g.title=j||"w3c";g.setAttribute("data-prefix",j);c[j]&&(g.className+=" selected");b.insertBefore(g,J.nextSibling)}var u=this;b.addEventListener("click",function(b){b=b.target;
if(b.nodeName=="SPAN")b=b.parentNode;if(b.nodeName=="A"){var c=b.getAttribute("data-prefix");(u.selected[c]=!u.selected[c])?b.className+=" selected":b.className=b.className.replace(" selected","");u.update()}},!1)}lb.prototype.update=function(){if(this.n){var b=[],c;for(c in this.selected)this.selected[c]&&b.push(c);this.n(b)}};
function nb(){var b=document.getElementById("sample-selector"),c={Sun:"m150,50 c 0 50 35 65 70 30 c -35 35 -20 70 30 70 c -50 0 -65 35 -30 70 c -35 -35 -70 -20 -70 30 c 0 -50 -35 -65 -70 -30 c 35 -35 20 -70 -30 -70 c 50 0 65 -35 30 -70 c 35 35 70 20 70 -30 l 0 50 a 50 50 0 0 1 0 100 a 50 50 0 0 1 0 -100 l 0 -50",CSS:"m120,110 c -4.368 -2.185 -10.784 -3.822 -18.429 -3.822 c -21.567 0 -35.9 13.787 -35.9 37.948 c 0 22.66 12.968 36.993 35.219 36.993c 7.371 0 14.742 -1.502 19.52 -3.822m 50 -68c -2.648 -1.601 -8.326 -3.942 -16.021 -3.942c -11.606 0 -16.021 6.775 -16.021 12.442c 0 7.761 5.173 11.58 16.904 16.014c 14.381 5.42 21.571 12.196 21.571 24.391c 0 12.812 -9.588 24.022 -29.646 24.022c -8.198 0 -17.155 -2.464 -21.696 -5.42m 100 -68c -2.648 -1.601 -8.326 -3.942 -16.021 -3.942c -11.606 0 -16.021 6.775 -16.021 12.442c 0 7.761 5.173 11.58 16.904 16.014c 14.381 5.42 21.571 12.196 21.571 24.391 c 0 12.812 -9.588 24.022 -29.646 24.022 c -8.198 0 -17.155 -2.464 -21.696 -5.42",
Circle:"m150,50 a 100 100 0 0 1 0 200 a 100 100 0 0 1 0 -200"},J;for(J in c){var j=c[J],g=document.createElementNS("http://www.w3.org/2000/svg","svg"),d=document.createElementNS("http://www.w3.org/2000/svg","path");g.appendChild(d);g.setAttribute("width","26");g.setAttribute("height","26");d.setAttribute("stroke","currentColor");d.setAttribute("stroke-linecap","round");d.setAttribute("stroke-linejoin","round");d.setAttribute("stroke-width","10");d.setAttribute("fill","none");d.setAttribute("transform",
"scale(0.1,0.1) translate(-20,-20)");d.setAttribute("d",j);d=document.createElement("a");d.appendChild(g);g=document.createElement("div");g.appendChild(document.createTextNode(J));d.appendChild(g);d.title=J;d.setAttribute("data-path",j);b.appendChild(d)}var u=this;b.addEventListener("click",function(b){for(b=b.target;b&&b.nodeName!="A";)b=b.parentNode;b&&(b=b.getAttribute("data-path"),u.n&&u.n(b))},!1)}
var Nb=function(){function b(a,e){var k,d,f,j,r,z,D,B;function A(i){aa=n;var L={a:0,ch:0};O(L,{a:p.length-1,ch:p[p.length-1].text.length},v(i),L,L);aa=new u}function C(){x.readOnly!="nocursor"&&(ba||(x.qa&&x.qa(X),ba=!0,$.className.search(/\bCodeMirror-focused\b/)==-1&&($.className+=" CodeMirror-focused"),Ga||Xa()),Na(),ob())}function F(){if(ba)x.oa&&x.oa(X),ba=!1,$.className=$.className.replace(" CodeMirror-focused","");clearInterval($a);setTimeout(function(){ba||(ga=n)},150)}function O(i,L,pb,a,
b){if(aa){for(var e=[],c=i.a,g=L.a+1;c<g;++c)e.push(p[c].text);for(aa.va(i.a,pb.length,e);aa.p.length>x.Va;)aa.p.shift()}qb(i,L,pb,a,b)}function S(i,L){var a=i.pop();if(a){for(var b=[],e=a.start+a.o,c=a.start;c<e;++c)b.push(p[c].text);L.push({start:a.start,o:a.m.length,m:b});b=b[b.length-1];if(c=a.m[a.m.length-1])if(b){for(var g=b.length,d=c.length;g>=0&&d>=0;--g,--d)if(b.charAt(g)!=c.charAt(d))break;b=d+1}else b=c.length;else b=b?b.length:0;b=R({a:a.start+a.m.length-1,ch:b});qb({a:a.start,ch:0},
{a:e-1,ch:p[e-1].text.length},a.m,b,b);ca=!0}}function rb(){S(aa.p,aa.M)}function sb(){S(aa.M,aa.p)}function qb(i,L,a,b,e){for(var d=!1,k=Ha.length,f=i.a;f<=L.a;++f)if(p[f].text.length==k){d=!0;break}var h=L.a-i.a,f=p[i.a],j=p[L.a];if(f==j)if(a.length==1)f.replace(i.ch,L.ch,a[0]);else{var j=f.split(L.ch,a[a.length-1]),l=[i.a+1,h];f.replace(i.ch,f.text.length,a[0]);for(var f=1,w=a.length-1;f<w;++f)l.push(new g(a[f]));l.push(j);p.splice.apply(p,l)}else if(a.length==1)f.replace(i.ch,f.text.length,a[0]+
j.text.slice(L.ch)),p.splice(i.a+1,h);else{l=[i.a+1,h-1];f.replace(i.ch,f.text.length,a[0]);j.replace(0,L.ch,a[a.length-1]);f=1;for(w=a.length-1;f<w;++f)l.push(new g(a[f]));p.splice.apply(p,l)}f=i.a;for(w=f+a.length;f<w;++f)if(j=p[f].text,j.length>k)Ha=j,k=j.length,ya=n,d=!1;if(d){k=0;Ha="";ya=n;f=0;for(w=p.length;f<w;++f)if(j=p[f].text,j.length>k)k=j.length,Ha=j}d=[];h=a.length-h-1;f=0;for(j=ha.length;f<j;++f)k=ha[f],k<i.a?d.push(k):k>L.a&&d.push(k+h);if(a.length<5){j=i.a;f=i.a+a.length;for(k=Oa(j);j<
f;++j)l=p[j],l.S(T,k),l.k=c(T,k);d.push(i.a+a.length)}else d.push(i.a);ha=d;ab(100);Y.push({b:i.a,c:L.a+1,Aa:h});bb={b:i,c:L,text:a};za(b,e,B.a<=Math.min(L.a,L.a+h)?B.a:B.a+h,D.a<=Math.min(L.a,L.a+h)?D.a:D.a+h);da.style.height=p.length*ea()+2*V.offsetTop+"px"}function qa(i,a,b){function e(f){if(E(f,a))return f;if(!E(b,f))return c;var Ob=f.a+i.length-(b.a-a.a)-1,d=f.ch;f.a==b.a&&(d+=i[i.length-1].length-(b.ch-(b.a==a.a?a.ch:0)));return{a:Ob,ch:d}}var a=R(a),b=b?R(b):a,i=v(i),c;tb(i,a,b,function(i){c=
i;return{b:e(B),c:e(D)}});return c}function Pa(i,a){tb(v(i),B,D,function(i){return a=="end"?{b:i,c:i}:a=="start"?{b:B,c:B}:{b:B,c:i}})}function tb(i,a,b,e){e=e({a:a.a+i.length-1,ch:i.length==1?i[0].length+a.ch:i[i.length-1].length});O(a,b,i,e.b,e.c)}function wa(i,a){var b=i.a,e=a.a;if(b==e)return p[b].text.slice(i.ch,a.ch);var c=[p[b].text.slice(i.ch)];for(b+=1;b<e;++b)c.push(p[b].text);c.push(p[e].text.slice(0,a.ch));return c.join("\n")}function ub(){return wa(B,D)}function Na(){cb||db.set(2E3,function(){eb();
vb();ba&&Na();fb()})}function Aa(i){function a(){eb();var e=vb();e&&i&&(e=="moved"&&va[i]==n&&(va[i]=!0),e=="changed"&&(va[i]=!1));!e&&!b?(b=!0,db.set(80,a)):(cb=!1,Na());fb()}var b=!1;cb=!0;db.set(20,a)}function vb(){function i(i,a){for(var L=0;;){var e=b.indexOf("\n",L);if(e==-1||(b.charAt(e-1)=="\r"?e-1:e)>=i)return{a:a,ch:i-L};++a;L=e+1}}if(!Ga&&ba){var a=!1,b=N.value,e=Ma(N);if(!e)return!1;var a=k!=b,c=ra,g=a||e.start!=d||e.end!=(c?d:f);if(!g&&!c)return!1;if(a&&(ga=ra=n,x.readOnly))return ca=
!0,"changed";var h=i(e.start,j),l=i(e.end,j);if(c){var o=e.start==c.anchor?l:h,l=ga?D:e.start==c.anchor?h:l;(z=E(o,l))?h=o:(ra=n,h=l,l=o)}h.a==l.a&&h.a==B.a&&h.a==D.a&&!ga&&(ca=!1);if(a){for(var o=0,c=b.length,s=Math.min(c,k.length),m,p=j,q=-1;o<s&&(m=b.charAt(o))==k.charAt(o);)++o,m=="\n"&&(p++,q=o);for(var s=q>-1?o-q:o,t=r-1,y=k.length;;){m=k.charAt(y);if(b.charAt(c)!=m){++c;++y;break}m=="\n"&&t--;if(y<=o||c<=o)break;--c;--y}q=k.lastIndexOf("\n",y-1);O({a:p,ch:s},{a:t,ch:q==-1?y:y-q-1},v(b.slice(o,
c)),h,l);if(p!=t||h.a!=p)ca=!0}else za(h,l);k=b;d=e.start;f=e.end;return a?"changed":g?"moved":!1}}function Xa(){for(var i=[],a=Math.max(0,B.a-1),b=Math.min(p.length,D.a+2),e=a;e<b;++e)i.push(p[e].text);for(var i=N.value=i.join(q),c=B.ch,h=D.ch,e=a;e<B.a;++e)c+=q.length+p[e].text.length;for(e=a;e<D.a;++e)h+=q.length+p[e].text.length;k=i;j=a;r=b;d=c;f=h;P(N,c,ra?c:h)}function Qa(){x.readOnly!="nocursor"&&N.focus()}function Pb(){if(ia.getBoundingClientRect){var i=ia.getBoundingClientRect(),a=window.innerHeight||
document.body.offsetHeight||document.documentElement.offsetHeight;(i.top<0||i.bottom>a)&&ia.scrollIntoView()}}function wb(){var i=gb(z?B:D);return xb(i.x,i.y,i.x,i.B)}function xb(i,a,b,e){var c=V.offsetLeft,f=V.offsetTop,h=ea();a+=f;e+=f;i+=c;b+=c;var d=I.clientHeight,g=I.scrollTop,c=!1,f=!0;if(a<g)I.scrollTop=Math.max(0,a-2*h),c=!0;else if(e>g+d)I.scrollTop=e+h-d,c=!0;a=I.clientWidth;e=I.scrollLeft;if(i<e)i<50&&(i=0),I.scrollLeft=Math.max(0,i-10),c=!0;else if(b>a+e)I.scrollLeft=b+10-a,c=!0,b>da.clientWidth&&
(f=!1);c&&x.K&&x.K(X);return f}function yb(){var i=ea(),a=I.scrollTop-V.offsetTop;return{b:Math.min(p.length,Math.max(0,Math.floor(a/i))),c:Math.min(p.length,Math.ceil((a+I.clientHeight)/i))}}function Ra(i){if(I.clientWidth){for(var a=i===!0?[]:[{b:U,c:ka,i:0}],b=0,e=i.length||0;b<e;++b){for(var c=i[b],f=[],h=c.Aa||0,d=0,g=a.length;d<g;++d){var k=a[d];c.c<=k.b?f.push({b:k.b+h,c:k.c+h,i:k.i}):k.c<=c.b?f.push(k):(c.b>k.b&&f.push({b:k.b,c:c.b,i:k.i}),c.c<k.c&&f.push({b:c.c+h,c:k.c+h,i:k.i+(c.c-k.b)}))}a=
f}for(var h=yb(),i=Math.min(U,Math.max(h.b-3,0)),c=Math.min(p.length,Math.max(ka,h.c+3)),f=[],d=0,g=ka-U,j=i,l=0,b=0,e=a.length;b<e;++b)if(k=a[b],!(k.c<=i)){if(k.b>=c)break;if(k.i>d||k.b>j)f.push({b:j,c:k.b,C:k.i-d,i:d}),l+=k.b-j;j=k.c;d=k.i+(k.c-k.b)}if(d!=g||j!=c)l+=Math.abs(c-j),f.push({b:j,c:c,C:g-d,i:d});if(f.length){W.style.display="none";if(l>(h.c-h.b)*0.3){k=i=Math.max(h.b-10,0);a=c=Math.min(h.c+7,p.length);b=[];e={a:k,ch:0};for(e=E(B,e)&&!E(D,e);k<a;++k){d=h=n;if(e){if(h=0,D.a==k)e=!1,d=
D.ch}else if(B.a==k)D.a==k?(h=B.ch,d=D.ch):(e=!0,h=B.ch);b.push(p[k].z(h,d,!0))}W.innerHTML=b.join("")}else{a=B.a;b=D.a;e=0;k=pa&&sa.createElement("div");h=0;for(d=f.length;h<d;++h){g=f[h];j=g.c-g.b-g.C;l=W.childNodes[g.i+g.C+e]||n;if(pa)for(var w=Math.max(-j,g.C);w>0;--w)W.removeChild(l?l.previousSibling:W.lastChild);else if(j){for(w=Math.max(0,j);w>0;--w)W.insertBefore(sa.createElement("pre"),l);for(w=Math.max(0,-j);w>0;--w)W.removeChild(l?l.previousSibling:W.lastChild)}for(var o=W.childNodes[g.i+
e],m=a<g.b&&b>=g.b,w=g.b;w<g.c;++w){var s=n,q=n;if(m){if(s=0,b==w)m=!1,q=D.ch}else if(a==w)b==w?(s=B.ch,q=D.ch):(m=!0,s=B.ch);pa?(k.innerHTML=p[w].z(s,q,!0),W.insertBefore(k.firstChild,l)):(o.innerHTML=p[w].z(s,q,!1),o.className=p[w].className||"",o=o.nextSibling)}e+=j}}W.style.display="";a=i!=U||c!=ka||zb!=I.clientHeight;U=i;ka=c;Sa.style.top=i*ea()+"px";if(a)zb=I.clientHeight,da.style.height=p.length*ea()+2*V.offsetTop+"px";(a||f.length)&&Ta();ya==n&&(ya=Ab(Ha));ya>I.clientWidth?(V.style.width=
ya+"px",da.style.width="",da.style.width=I.scrollWidth+"px"):V.style.width=da.style.width="";if(W.childNodes.length!=ka-U)throw Error("BAD PATCH! "+JSON.stringify(f)+" size="+(ka-U)+" nodes="+W.childNodes.length);Bb()}}else U=ka=0}function Ta(){if(x.R||x.J){var i=Sa.offsetHeight,a=I.clientHeight;la.style.height=(i-a<2?a:i)+"px";i=[];for(a=U;a<Math.max(ka,U+1);++a){var b=p[a].H,e=x.J?a+x.Ea:n;b&&b.text?e=b.text.replace("%N%",e!=n?e:""):e==n&&(e="\u00a0");i.push(b&&b.style?'<pre class="'+b.style+'">':
"<pre>",e,"</pre>")}la.style.display="none";Ua.innerHTML=i.join("");i=String(p.length).length;a=Ua.firstChild;b=a.textContent||a.innerText||a.nodeValue||"";for(e="";b.length+e.length<i;)e+="\u00a0";e&&a.insertBefore(sa.createTextNode(e),a.firstChild);la.style.display="";V.style.marginLeft=la.offsetWidth+"px"}}function Bb(){var i=z?B:D,a=ea(),b=Cb(i.a,i.ch);Ia.style.top=i.a*a-I.scrollTop+"px";Ia.style.left=b-I.scrollLeft+"px";M(B,D)?(ia.style.top=(i.a-U)*a+"px",ia.style.left=b+"px",ia.style.display=
""):ia.style.display="none"}function Ba(i,a){var b=ga&&R(ga);b&&(E(b,i)?i=b:E(a,b)&&(a=b));za(i,a)}function za(i,a,b,e){if(!M(B,i)||!M(D,a)){if(E(a,i))var c=a,a=i,i=c;M(i,a)?z=!1:M(i,D)?z=!1:M(a,B)&&(z=!0);if(b==n)b=B.a,e=D.a;M(i,a)?M(B,D)||Y.push({b:b,c:e+1}):M(B,D)?Y.push({b:i.a,c:a.a+1}):(M(i,B)||(i.a<b?Y.push({b:i.a,c:Math.min(a.a,b)+1}):Y.push({b:b,c:Math.min(e,i.a)+1})),M(a,D)||(a.a<e?Y.push({b:Math.max(b,i.a),c:e+1}):Y.push({b:Math.max(i.a,e),c:a.a+1})));B=i;D=a;ma=!0}}function ta(i,a,b){i=
R({a:i,ch:a||0});(b?Ba:za)(i,i)}function ua(i){return Math.max(0,Math.min(i,p.length-1))}function R(i){if(i.a<0)return{a:0,ch:0};if(i.a>=p.length)return{a:p.length-1,ch:p[p.length-1].text.length};var a=i.ch,b=p[i.a].text.length;return a==n||a>b?{a:i.a,ch:b}:a<0?{a:i.a,ch:0}:i}function Qb(i){Ba({a:i,ch:0},{a:i,ch:p[i].text.length})}function Rb(i){function a(i){if(M(B,D))Ca(B.a,i);else for(var b=D.a-(D.ch?0:1),e=B.a;e<=b;++e)Ca(e,i)}ga=n;switch(x.ta){case "default":return!1;case "indent":a("smart");
break;case "classic":if(M(B,D)){i?Ca(B.a,"smart"):Pa("\t","end");break}case "shift":a(i?"subtract":"add")}return!0}function Ca(i,a){if(a=="smart")if(T.la)var b=Oa(i);else a="prev";var e=p[i],c=e.I(),f=e.text.match(/^\s*/)[0],k;a=="prev"?k=i?p[i-1].I():0:a=="smart"?k=T.la(b,e.text.slice(f.length)):a=="add"?k=c+x.T:a=="subtract"&&(k=c-x.T);k=Math.max(0,k);if(k-c){c="";b=0;if(x.Ha)for(e=Math.floor(k/h);e;--e)b+=h,c+="\t";for(;b<k;)++b,c+=" "}else{if(B.a!=i&&D.a!=i)return;c=f}qa(c,{a:i,ch:0},{a:i,ch:f.length})}
function Db(){T=b.ja(x,x.mode);for(var i=0,a=p.length;i<a;++i)p[i].k=n;ha=[0];ab()}function hb(i,a,b){function e(i,a,b,f){i=p[i];a=i.wa(a,b,f);a.a=i;c.push(a)}var i=R(i),a=R(a),c=[];if(i.a==a.a)e(i.a,i.ch,a.ch,b);else{e(i.a,i.ch,n,b);for(var f=i.a+1,k=a.a;f<k;++f)e(f,0,n,b);e(a.a,0,a.ch,b)}Y.push({b:i.a,c:a.a+1});return function(){for(var i,a,b=0;b<c.length;++b){var e=c[b],f=Z(p,e.a);e.a.Ma(e);f>-1&&(i==n&&(i=f),a=f)}i!=n&&Y.push({b:i,c:a+1})}}function Ab(i){ja.innerHTML="<pre><span>x</span></pre>";
ja.firstChild.firstChild.firstChild.nodeValue=i;return ja.firstChild.firstChild.offsetWidth||10}function Cb(i,a){if(a==0)return 0;ja.innerHTML="<pre><span>"+p[i].z(n,n,!1,a)+"</span></pre>";return ja.firstChild.firstChild.offsetWidth}function Eb(i,a){function b(a){ja.innerHTML="<pre><span>"+e.z(n,n,!1,a)+"</span></pre>";return ja.firstChild.firstChild.offsetWidth}if(a<=0)return 0;for(var e=p[i],c=0,f=0,k=e.text.length,h,d=Math.min(k,Math.ceil(a/Ab("x")));;){var g=b(d);if(g<=a&&d<k)d=Math.min(k,Math.ceil(d*
1.2));else{h=g;k=d;break}}if(a>h)return k;d=Math.floor(k*0.8);g=b(d);g<a&&(c=d,f=g);for(;;){if(k-c<=1)return h-a>a-f?c:k;d=Math.ceil((c+k)/2);g=b(d);g>a?(k=d,h=g):(c=d,f=g)}}function gb(a,b){var e=ea(),c=a.a-(b?U:0);return{x:Cb(a.a,a.ch),y:c*e,B:(c+1)*e}}function Fb(a){var a=gb(a,!0),b=G(V);return{x:b.left+a.x,y:b.top+a.y,B:b.top+a.B}}function ea(){var a=W.childNodes.length;if(a)return W.offsetHeight/a||1;ja.innerHTML="<pre>x</pre>";return ja.firstChild.offsetHeight||1}function Da(a,b){var e=G(I,
!0),c,f;try{c=a.clientX,f=a.clientY}catch(k){return n}if(!b&&(c-e.left>I.clientWidth||f-e.top>I.clientHeight))return n;e=G(V,!0);f=U+Math.floor((f-e.top)/ea());return R({a:f,ch:Eb(ua(f),c-e.left)})}function Gb(a){function b(){var a=v(N.value).join("\n");a!=f&&K(Pa)(a,"end");Ia.style.position="relative";N.style.cssText=c;Ga=!1;Xa();Na()}var e=Da(a);if(e&&!window.opera){(M(B,D)||E(e,B)||!E(e,D))&&K(ta)(e.a,e.ch);var c=N.style.cssText;Ia.style.position="absolute";N.style.cssText="position: fixed; width: 30px; height: 30px; top: "+
(a.clientY-5)+"px; left: "+(a.clientX-5)+"px; z-index: 1000; background: white; border-width: 0; outline: none; overflow: hidden; opacity: .05; filter: alpha(opacity=5);";Ga=!0;var f=N.value=ub();Qa();P(N,0,N.value.length);if(s){t(a);var k=m(window,"mouseup",function(){k();setTimeout(b,20)},!0)}else setTimeout(b,50)}}function ob(){clearInterval($a);var a=!0;ia.style.visibility="";$a=setInterval(function(){ia.style.visibility=(a=!a)?"":"hidden"},650)}function Hb(a){function b(a,i,e){if(a.text)for(var c=
a.q,a=d?0:a.text.length-1,f,k=d?0:c.length-2,g=d?c.length:-2;k!=g;k+=2*h){var j=c[k];if(c[k+1]!=n&&c[k+1]!=w)a+=h*j.length;else for(var l=d?0:j.length-1,L=d?j.length:-1;l!=L;l+=h,a+=h)if(a>=i&&a<e&&s.test(f=j.charAt(l))){var m=ib[f];if(m.charAt(1)==">"==d)o.push(f);else if(o.pop()!=m.charAt(0))return{d:a,match:!1};else if(!o.length)return{d:a,match:!0}}}}var e=z?B:D,c=p[e.a],f=e.ch-1,k=f>=0&&ib[c.text.charAt(f)]||ib[c.text.charAt(++f)];if(k){for(var d=k.charAt(1)==">",h=d?1:-1,g=c.q,j=f+1,k=0,l=g.length;k<
l;k+=2)if((j-=g[k].length)<=0){var w=g[k+1];break}for(var o=[c.text.charAt(f)],s=/[(){}[\]]/,k=e.a,l=d?Math.min(k+100,p.length):Math.max(-1,k-100);k!=l;k+=h){var c=p[k],m=k==e.a;if(m=b(c,m&&d?f+1:0,m&&!d?f:c.text.length))break}m||(m={d:n,match:!1});var w=m.match?"CodeMirror-matchingbracket":"CodeMirror-nonmatchingbracket",q=hb({a:e.a,ch:f},{a:e.a,ch:f+1},w),r=m.d!=n?hb({a:k,ch:m.d},{a:k,ch:m.d+1},w):function(){},e=K(function(){q();r()});a?setTimeout(e,800):Va=e}}function Ib(a){var b,e,c=a;for(a-=
40;c>a;--c){if(c==0)return 0;var f=p[c-1];if(f.k)return c;f=f.I();if(e==n||b>f)e=c-1,b=f}return e}function Oa(a){for(var b=Ib(a),e=b&&p[b-1].k,e=e?c(T,e):J(T);b<a;++b){var f=p[b];f.S(T,e);f.k=c(T,e)}a<p.length&&!p[a].k&&ha.push(a);return e}function Sb(){for(var a=+new Date+x.Xa,b=ha.length;ha.length;){var e=p[U].k?ha.pop():U;if(!(e>=p.length)){for(var f=Ib(e),k=f&&p[f-1].k,k=k?c(T,k):J(T),d=0,h=T.hb,g=!1,j=p.length;f<j;++f){var l=p[f],w=l.k;if(+new Date>a){ha.push(f);ab(x.Wa);g&&Y.push({b:e,c:f+1});
return}var o=l.S(T,k);o&&(g=!0);l.k=c(T,k);if(h){if(w&&h(w,k))break}else if(o!==!1||!w)d=0;else if(++d>3)break}g&&Y.push({b:e,c:f+1})}}b&&x.sa&&x.sa(X)}function ab(a){ha.length&&Tb.set(a,K(Sb))}function eb(){ca=n;Y=[];bb=ma=!1}function fb(){var a=!1;ma&&(a=!wb());Y.length?Ra(Y):ma&&Bb();a&&wb();ma&&(Pb(),ob());ba&&!Ga&&(ca===!0||ca!==!1&&ma)&&Xa();ma&&x.ma&&setTimeout(K(function(){Va&&(Va(),Va=n);Hb(!1)}),20);a=bb;ma&&x.pa&&x.pa(X);a&&x.n&&X&&x.n(X,a)}function K(a){return function(){Jb++||eb();try{var b=
a.apply(this,arguments)}finally{--Jb||fb()}return b}}function Kb(a,b,e){this.v=!1;e==n&&(e=typeof a=="string"&&a==a.toLowerCase());b=b&&typeof b=="object"?R(b):{a:0,ch:0};this.d={b:b,c:b};if(typeof a!="string")this.na=function(b,e){if(b)for(var c=p[e.a].text.slice(0,e.ch),f=c.match(a),k=0;f;){var d=c.indexOf(f[0]);k+=d;c=c.slice(d+1);if(d=c.match(a))f=d;else break;k++}else c=p[e.a].text.slice(e.ch),k=(f=c.match(a))&&e.ch+c.indexOf(f[0]);if(f)return{b:{a:e.a,ch:k},c:{a:e.a,ch:k+f[0].length},match:f}};
else{e&&(a=a.toLowerCase());var c=e?function(a){return a.toLowerCase()}:function(a){return a},f=a.split("\n");this.na=f.length==1?function(b,e){var f=c(p[e.a].text),k=a.length,d;if(b?e.ch>=k&&(d=f.lastIndexOf(a,e.ch-k))!=-1:(d=f.indexOf(a,e.ch))!=-1)return{b:{a:e.a,ch:d},c:{a:e.a,ch:d+k}}}:function(a,b){var e=b.a,i=a?f.length-1:0,k=f[i],d=c(p[e].text),h=a?d.indexOf(k)+k.length:d.lastIndexOf(k);if(!(a?h>=b.ch||h!=k.length:h<=b.ch||h!=d.length-k.length))for(;;){if(a?!e:e==p.length-1)break;d=c(p[e+=
a?-1:1].text);k=f[a?--i:++i];if(i>0&&i<f.length-1)if(d!=k)break;else continue;i=a?d.lastIndexOf(k):d.indexOf(k)+k.length;if(a?i!=d.length-k.length:i!=k.length)break;k={a:b.a,ch:h};e={a:e,ch:i};return{b:a?e:k,c:a?k:e}}}}}var x={},jb=b.O,Ja;for(Ja in jb)jb.hasOwnProperty(Ja)&&(x[Ja]=(e&&e.hasOwnProperty(Ja)?e:jb)[Ja]);var sa=x.document,$=sa.createElement("div");$.className="CodeMirror";$.innerHTML='<div style="overflow: hidden; position: relative; width: 1px; height: 0px;"><textarea style="position: absolute; width: 2px;" wrap="off"></textarea></div><div class="CodeMirror-scroll cm-s-'+
x.Ra+'"><div style="position: relative"><div style="position: absolute; height: 0; width: 0; overflow: hidden;"></div><div style="position: relative"><div class="CodeMirror-gutter"><div class="CodeMirror-gutter-text"></div></div><div class="CodeMirror-lines"><div style="position: relative"><pre class="CodeMirror-cursor">&#160;</pre><div></div></div></div></div></div></div>';a.appendChild?a.appendChild($):a($);var Ia=$.firstChild,N=Ia.firstChild,I=$.lastChild,da=I.firstChild,ja=da.firstChild,Sa=ja.nextSibling,
la=Sa.firstChild,Ua=la.firstChild,V=la.nextSibling.firstChild,ia=V.firstChild,W=ia.nextSibling;if(x.t!=n)N.t=x.t;if(!x.R&&!x.J)la.style.display="none";var db=new H,Tb=new H,$a,T,p=[new g("")],ha,aa=new u,ba;Db();B={a:0,ch:0};D={a:0,ch:0};z=!1;var ga,ra,kb,ca,Y,bb,ma,Ga,U=0,ka=0,zb=0,Ka=n,Va,Ha="",ya;K(function(){A(x.value||"");ca=!1})();m(I,"mousedown",K(function(a){function e(a){var b=Da(a,!0);if(b&&!M(b,k)){ba||C();k=b;Ba(f,b);ca=!1;var i=yb();if(b.a>=i.c||b.a<i.b)d=setTimeout(K(function(){e(a)}),
150)}}for(var b=a.target||a.srcElement;b!=$;b=b.parentNode)if(b.parentNode==da&&b!=Sa)return;var c=kb;kb=n;for(b=a.target||a.srcElement;b!=$;b=b.parentNode)if(b.parentNode==Ua)return x.ra&&x.ra(X,Z(Ua.childNodes,b)+U),o(a);var f=Da(a);switch(Q(a)){case 3:s&&!l&&Gb(a);return;case 2:f&&ta(f.a,f.ch,!0);return}if(f){ba||C();o(a);if(c&&+new Date-c<400)return Qb(f.a);ta(f.a,f.ch,!0);var k=f,d,h=m(sa,"mousemove",K(function(a){clearTimeout(d);o(a);e(a)}),!0),g=m(sa,"mouseup",K(function(a){clearTimeout(d);
var b=Da(a);b&&Ba(f,b);o(a);Qa();ca=!0;h();g()}),!0)}else(a.target||a.srcElement)==I&&o(a)}));s||m(I,"contextmenu",Gb);m(da,"dblclick",K(function(a){var b=Da(a);if(b){for(var e=p[b.a].text,c=b.ch,f=b.ch;c>0&&/\w/.test(e.charAt(c-1));)--c;for(;f<e.length&&/\w/.test(e.charAt(f));)++f;Ba({a:b.a,ch:c},{a:b.a,ch:f});o(a);kb=+new Date}}));m(I,"scroll",function(){Ra([]);x.K&&x.K(X)});m(window,"resize",function(){Ra(!0)});m(N,"keyup",K(function(a){if(!x.u||!x.u(X,y(a)))ra&&(ra=n,ca=!0),a.keyCode==16&&(ga=
n)}));m(N,"keydown",K(function(a){ba||C();var b=a.keyCode;if(Mb&&b==27)a.returnValue=!1;var e=(l?a.metaKey:a.ctrlKey)&&!a.altKey,c=a.ctrlKey||a.altKey||a.metaKey;ga=b==16||a.shiftKey?ga||(z?D:B):n;if(!x.u||!x.u(X,y(a))){if(b==33||b==34)return e=b==34,b=Math.floor(I.clientHeight/ea()),c=z?B:D,ta(c.a+Math.max(b-1,1)*(e?1:-1),c.ch,!0),o(a);if(e&&(b==36||b==35||l&&(b==38||b==40)))return e=b==36||b==38?{a:0,ch:0}:{a:p.length-1,ch:p[p.length-1].text.length},Ba(e,e),o(a);if(e&&b==65)return e=p.length-1,
za({a:0,ch:0},{a:e,ch:p[e].text.length}),o(a);if(!x.readOnly){if(!c&&b==13)return;if(!c&&b==9&&Rb(a.shiftKey))return o(a);if(e&&b==90)return rb(),o(a);if(e&&(a.shiftKey&&b==90||b==89))return sb(),o(a)}if(b==36&&x.Pa)return e=Math.max(0,p[B.a].text.search(/\S/)),ta(B.a,B.ch<=e&&B.ch?0:e,!0),o(a);Ka=(e?"c":"")+(a.altKey?"a":"")+b;if(z&&va[Ka]===!0&&(b=Ma(N)))ra={anchor:b.start},P(N,b.start,b.start);!e&&!a.altKey&&(Ka=n);Aa(Ka)}}));m(N,"keypress",K(function(a){if(!x.u||!x.u(X,y(a))){x.F&&T.F&&T.F.indexOf(String.fromCharCode(a.charCode==
n?a.keyCode:a.charCode))>-1&&setTimeout(K(function(){Ca(D.a,"smart")}),50);var b=a.keyCode;b==13?(x.readOnly||(Pa("\n","end"),x.ha!="flat"&&Ca(B.a,x.ha=="keep"?"prev":"smart")),o(a)):!a.ctrlKey&&!a.altKey&&!a.metaKey&&b==9&&x.ta!="default"?o(a):Aa(Ka)}}));m(N,"focus",C);m(N,"blur",F);m(I,"dragenter",t);m(I,"dragover",t);m(I,"drop",K(function(a){a.preventDefault();var b=Da(a,!0),e=a.dataTransfer.files;if(b&&!x.readOnly)if(e&&e.length&&window.Za&&window.Ya)for(var a=function(a,e){var i=new FileReader;
i.onload=function(){f[e]=i.result;++k==c&&qa(f.join(""),R(b),R(b))};i.readAsText(a)},c=e.length,f=Array(c),k=0,d=0;d<c;++d)a(e[d],d);else try{(f=a.dataTransfer.getData("Text"))&&qa(f,b,b)}catch(h){}}));m(I,"paste",function(){Qa();Aa()});m(N,"paste",function(){Aa()});m(N,"cut",function(){Aa()});var Lb;try{Lb=sa.activeElement==N}catch(Ub){}Lb?setTimeout(C,20):F();var X={Q:function(){for(var a=[],b=0,e=p.length;b<e;++b)a.push(p[b].text);return a.join("\n")},Z:K(A),getSelection:ub,Nb:K(Pa),focus:function(){Qa();
C();Aa()},Ub:function(a,b){x[a]=b;if(a=="lineNumbers"||a=="gutter"||a=="firstLineNumber"){var e=x.R||x.J;la.style.display=e?"":"none";e?Ta():W.parentNode.style.marginLeft=0}else if(a=="mode"||a=="indentUnit")Db();else if(a=="readOnly"&&b=="nocursor")N.blur();else if(a=="theme")I.className=I.className.replace(/cm-s-\w+/,"cm-s-"+b)},tb:function(a){return x[a]},Ua:K(rb),La:K(sb),Bb:K(function(a,b){a>=0&&a<p.length&&Ca(a,b==n?"smart":b?"add":"subtract")}),zb:function(){return{Ua:aa.p.length,La:aa.M.length}},
ma:K(function(){Hb(!0)}),ka:function(a){a=R(a);return p[a.a].ka(T,Oa(a.a),a.ch)},wb:function(a){a=ua(a==n?p.length-1:a);return Oa(a+1)},lb:function(a){a==n&&(a=z);return Fb(a?B:D)},fb:function(a){return Fb(R(a))},ib:function(a){var b=G(V),e=ua(Math.min(p.length-1,U+Math.floor((a.y-b.top)/ea())));return R({a:e,ch:Eb(ua(e),a.x-b.left)})},Fa:function(a,b,e){return new Kb(a,b,e)},Gb:K(function(a,b,e){return K(hb(a,b,e))}),Tb:function(a,b,e){typeof a=="number"&&(a=p[ua(a)]);a.H={text:b,style:e};Ta();return a},
gb:function(a){typeof a=="number"&&(a=p[ua(a)]);a.H=n;Ta()},Sb:K(function(a,b){if(typeof a=="number")var e=a,a=p[ua(a)];else if(e=Z(p,a),e==-1)return n;if(a.className!=b)a.className=b,Y.push({b:e,c:e+1});return a}),Db:function(a){if(typeof a=="number"){var b=a,a=p[a];if(!a)return n}else if(b=Z(p,a),b==-1)return n;var e=a.H;return{a:b,text:a.text,Ib:e&&e.text,Hb:e&&e.style}},cb:function(a,b,e,c){var a=gb(R(a)),f=a.B,k=a.x;b.style.position="absolute";da.appendChild(b);b.style.left=k+"px";if(c=="over")f=
a.y;else if(c=="near"){var c=Math.max(I.offsetHeight,p.length*ea()),d=Math.max(da.clientWidth,V.clientWidth)-V.offsetLeft;a.B+b.offsetHeight>c&&a.y>b.offsetHeight&&(f=a.y-b.offsetHeight);k+b.offsetWidth>d&&(k=d-b.offsetWidth)}b.style.top=f+V.offsetTop+"px";b.style.left=k+V.offsetLeft+"px";e&&xb(k,f,k+b.offsetWidth,f+b.offsetHeight)},V:function(){return p.length},qb:function(a){a==n&&(a=z);return{a:(a?B:D).a,ch:(a?B:D).ch}},Vb:function(){return!M(B,D)},Qb:K(function(a,b){b==n&&typeof a.a=="number"?
ta(a.a,a.ch):ta(a,b)}),Y:K(function(a,b){za(R(a),R(b||a))}),G:function(a){if(a>=0&&a<p.length)return p[a].text},Rb:K(function(a,b){a>=0&&a<p.length&&qa(b,{a:a,ch:0},{a:a,ch:p[a].text.length})}),Lb:K(function(a){a>=0&&a<p.length&&qa("",{a:a,ch:0},R({a:a+1,ch:0}))}),Mb:K(qa),ub:function(a,b){return wa(R(a),R(b))},Jb:function(a){return K(a)()},refresh:function(){Ra(!0)},sb:function(){return N},Ga:function(){return $},vb:function(){return I},rb:function(){return la}},cb=!1,ib={"(":")>",")":"(<","[":"]>",
"]":"[<","{":"}>","}":"{<"},Jb=0;Kb.prototype={Da:function(){return this.find(!1)},find:function(a){function b(a){a={a:a,ch:0};e.d={b:a,c:a};return e.v=!1}for(var e=this,c=R(a?this.d.b:this.d.c);;){if(this.d=this.na(a,c))return this.v=!0,this.d.match||!0;if(a){if(!c.a)return b(0);c={a:c.a-1,ch:p[c.a-1].text.length}}else{if(c.a==p.length-1)return b(p.length);c={a:c.a+1,ch:0}}}},b:function(){if(this.v)return{a:this.d.b.a,ch:this.d.b.ch}},c:function(){if(this.v)return{a:this.d.c.a,ch:this.d.c.ch}},replace:function(a){var b=
this;this.v&&K(function(){b.d.c=qa(a,b.d.b,b.d.c)})()}};for(var Wa in fa)fa.propertyIsEnumerable(Wa)&&!X.propertyIsEnumerable(Wa)&&(X[Wa]=fa[Wa]);return X}function c(a,b){if(b===!0)return b;if(a.da)return a.da(b);var c={},d;for(d in b){var f=b[d];f instanceof Array&&(f=f.concat([]));c[d]=f}return c}function J(a,b,c){return a.$?a.$(b,c):!0}function j(a){this.d=this.start=0;this.j=a}function g(a,b){this.q=b||[a,n];this.k=n;this.text=a;this.s=this.H=this.className=n}function d(a,b,c,d){for(var f=0,h=
0,g=0;h<b;f+=2){var j=c[f],l=h+j.length;g==0?(l>a&&d.push(j.slice(a-h,Math.min(j.length,b-h)),c[f+1]),l>=a&&(g=1)):g==1&&(l>b?d.push(j.slice(0,b-h),c[f+1]):d.push(j,c[f+1]));h=l}}function u(){this.ua=0;this.p=[];this.M=[]}function A(){t(this)}function y(a){if(!a.stop)a.stop=A;return a}function o(a){a.preventDefault?a.preventDefault():a.returnValue=!1}function t(a){o(a);a.stopPropagation?a.stopPropagation():a.cancelBubble=!0}function Q(a){if(a.which)return a.which;else if(a.button&1)return 1;else if(a.button&
2)return 3;else if(a.button&4)return 2}function m(a,b,c,d){function f(a){c(a||window.event)}if(typeof a.addEventListener=="function"){if(a.addEventListener(b,f,!1),d)return function(){a.removeEventListener(b,f,!1)}}else if(a.attachEvent("on"+b,f),d)return function(){a.detachEvent("on"+b,f)}}function H(){this.id=n}function C(a){var b;if(b==n&&(b=a.search(/[^\s\u00a0]/),b==-1))b=a.length;for(var c=0,d=0;c<b;++c)a.charAt(c)=="\t"?d+=h-d%h:++d;return d}function G(a,b){for(var c=a.ownerDocument.body,d=
0,f=0,h=!1,g=a;g;g=g.offsetParent)d+=g.offsetLeft,f+=g.offsetTop,b&&(g.currentStyle?g.currentStyle:window.getComputedStyle(g,n)).position=="fixed"&&(h=!0);c=b&&!h?n:c;for(g=a.parentNode;g!=c;g=g.parentNode)g.scrollLeft!=n&&(d-=g.scrollLeft,f-=g.scrollTop);return{left:d,top:f}}function M(a,b){return a.a==b.a&&a.ch==b.ch}function E(a,b){return a.a<b.a||a.a==b.a&&a.ch<b.ch}function F(a){wa.innerText=wa.textContent=a;return wa.innerHTML}function Z(a,b){if(a.indexOf)return a.indexOf(b);for(var c=0,d=a.length;c<
d;++c)if(a[c]==b)return c;return-1}b.O={value:"",mode:n,Ra:"default",T:2,Ha:!1,ta:"classic",ha:"indent",F:!0,u:n,J:!1,R:!1,Ea:1,readOnly:!1,Pa:!0,n:n,pa:n,ra:n,sa:n,qa:n,oa:n,K:n,ma:!1,Xa:100,Wa:200,Va:40,t:n,document:window.document};var S={},O={};b.P=function(a,e){if(!b.O.mode&&a!="null")b.O.mode=a;S[a]=e};b.fa=function(a,b){O[a]=b};b.ja=function(a,e){typeof e=="string"&&O.hasOwnProperty(e)&&(e=O[e]);if(typeof e=="string")var c=e,d={};else if(e!=n)c=e.name,d=e;var f=S[c];return!f?(window.console&&
console.warn("No mode "+c+" found, falling back to plain text."),b.ja(a,"text/plain")):f(a,d||{})};b.Fb=function(){var a=[],b;for(b in S)S.propertyIsEnumerable(b)&&a.push(b);return a};b.Eb=function(){var a=[],b;for(b in O)O.propertyIsEnumerable(b)&&a.push(b);return a};var fa={};b.nb=function(a,b){fa[a]=b};b.pb=function(a,e){function c(){a.value=h.Q()}e||(e={});e.value=a.value;if(!e.t&&a.t)e.t=a.t;if(a.form){var d=m(a.form,"submit",c,!0);if(typeof a.form.submit=="function"){var f=a.form.submit,g=function(){c();
a.form.submit=f;a.form.submit();a.form.submit=g};a.form.submit=g}}a.style.display="none";var h=b(function(b){a.parentNode.insertBefore(b,a.nextSibling)},e);h.save=c;h.Yb=function(){c();a.parentNode.removeChild(h.Ga());a.style.display="";if(a.form&&(d(),typeof a.form.submit=="function"))a.form.submit=f};return h};b.$=J;b.da=c;j.prototype={ia:function(){return this.d>=this.j.length},next:function(){if(this.d<this.j.length)return this.j.charAt(this.d++)},w:function(a){var b=this.j.charAt(this.d);if(typeof a==
"string"?b==a:b&&(a.test?a.test(b):a(b)))return++this.d,b},D:function(a){for(var b=this.d;this.w(a););return this.d>b},ga:function(){for(var a=this.d;/[\s\u00a0]/.test(this.j.charAt(this.d));)++this.d;return this.d>a},Oa:function(){this.d=this.j.length},I:function(){return C(this.j)},match:function(a,b,c){if(typeof a=="string"){if((c?this.j.toLowerCase():this.j).indexOf(c?a.toLowerCase():a,this.d)==this.d)return b!==!1&&(this.d+=a.length),!0}else return(a=this.j.slice(this.d).match(a))&&b!==!1&&(this.d+=
a[0].length),a},ea:function(){return this.j.slice(this.start,this.d)}};b.$a=j;g.prototype={replace:function(a,b,c){var h=[],f=this.s;d(0,a,this.q,h);c&&h.push(c,n);d(b,this.text.length,this.q,h);this.q=h;this.text=this.text.slice(0,a)+c+this.text.slice(b);this.k=n;if(f){a=c.length-(b-a);c=this.text.length;for(h=0;h<f.length;++h){var g=f[h],j=!1;if(g.b>=c)j=!0;else if(g.b=g.b<=Math.min(b,b+a)?g.b:g.b+a,g.c!=n)g.c=g.c<=Math.min(b,b+a)?g.c:g.c+a;if(j||g.b>=g.c)f.splice(h,1),h--}}},split:function(a,b){var c=
[b,n];d(a,this.text.length,this.q,c);return new g(b+this.text.slice(a),c)},wa:function(a,b,c){a={b:a,c:b,style:c};if(this.s==n)this.s=[];this.s.push(a);this.s.sort(function(a,b){return a.b-b.b});return a},Ma:function(a){var b=this.s;if(b)for(var c=0;c<b.length;++c)if(b[c]==a){b.splice(c,1);break}},S:function(a,b){var c=new j(this.text),d=this.q,f=0,h=!1,g=d[0],l;for(this.text==""&&a.ya&&a.ya(b);!c.ia();){var o=a.L(c,b),m=this.text.slice(c.start,c.d);c.start=c.d;if(f&&d[f-1]==o)d[f-2]+=m;else if(m){if(!h&&
(d[f+1]!=o||f&&d[f-2]!=l))h=!0;d[f++]=m;d[f++]=o;l=g;g=d[f]}if(c.d>5E3){d[f++]=this.text.slice(c.d);d[f++]=n;break}}if(d.length!=f)d.length=f,h=!0;f&&d[f-2]!=l&&(h=!0);return h||(d.length<5&&this.text.length<10?n:!1)},ka:function(a,b,c){for(var d=new j(this.text);d.d<c&&!d.ia();){d.start=d.d;var f=a.L(d,b)}return{start:d.start,end:d.d,j:d.ea(),className:f||n,state:b}},I:function(){return C(this.text)},z:function(a,b,c,d){function f(a,b){a&&(b?h.push('<span class="',b,'">',F(a),"</span>"):h.push(F(a)))}
var h=[];c&&h.push(this.className?'<pre class="'+this.className+'">':"<pre>");var g=this.q,j=this.text,l=this.s;a==b&&(a=n);var o=j.length;d!=n&&(o=Math.min(d,o));if(!j&&d==n)f(" ",a!=n&&b==n?"CodeMirror-selected":n);else if(!l&&a==n)for(a=d=0;a<o;d+=2){var b=g[d],m=b.length;a+m>o&&(b=b.slice(0,o-a));a+=m;f(b,"cm-"+g[d+1])}else{var d=j=0,s="",q=-1,r=n,t=function(){l&&(q+=1,r=q<l.length?l[q]:n)};for(t();j<o;){var y=o,z="";if(a!=n)if(a>j)y=a;else if(b==n||b>j)z=" CodeMirror-selected",b!=n&&(y=Math.min(y,
b));for(;r&&r.c!=n&&r.c<=j;)t();r&&(r.b>j?y=Math.min(y,r.b):(z+=" "+r.style,r.c!=n&&(y=Math.min(y,r.c))));for(;;){var u=j+s.length,v=m;z&&(v=m?m+z:z);f(u>y?s.slice(0,y-j):s,v);if(u>=y){s=s.slice(y-j);j=y;break}j=u;s=g[d++];m="cm-"+g[d++]}}a!=n&&b==n&&f(" ","CodeMirror-selected")}c&&h.push("</pre>");return h.join("")}};u.prototype={va:function(a,b,c){this.M.length=0;var d=+new Date,f=this.p[this.p.length-1];if(d-this.ua>400||!f||f.start>a+b||f.start+f.o<a-f.o+f.m.length)this.p.push({start:a,o:b,m:c});
else{var h=0;if(a<f.start){for(var g=f.start-a-1;g>=0;--g)f.m.unshift(c[g]);f.o+=f.start-a;f.start=a}else f.start<a&&(h=a-f.start,b+=h);g=f.o-h;for(a=c.length;g<a;++g)f.m.push(c[g]);if(f.o<b)f.o=b}this.ua=d}};H.prototype={set:function(a,b){clearTimeout(this.id);this.id=setTimeout(b,a)}};var pa=function(){var a=document.createElement("pre");a.innerHTML=" ";return!a.innerHTML}(),s=/gecko\/\d{7}/i.test(navigator.userAgent),Mb=/MSIE \d/.test(navigator.userAgent),z=/Apple Computer/.test(navigator.vendor),
q="\n";(function(){var a=document.createElement("textarea");a.value="foo\nbar";a.value.indexOf("\r")>-1&&(q="\r\n")})();for(var h=8,l=/Mac/.test(navigator.platform),va={},r=35;r<=40;++r)va[r]=va["c"+r]=!0;var wa=document.createElement("div");b.Ab=F;var v,Ma,P;v="\n\nb".split(/\n/).length!=3?function(a){for(var b=0,c,d=[];(c=a.indexOf("\n",b))>-1;)d.push(a.slice(b,a.charAt(c-1)=="\r"?c-1:c)),b=c+1;d.push(a.slice(b));return d}:function(a){return a.split(/\r?\n/)};b.Wb=v;window.getSelection?(Ma=function(a){try{return{start:a.selectionStart,
end:a.selectionEnd}}catch(b){return n}},P=z?function(a,b,c){b==c?a.setSelectionRange(b,c):(a.setSelectionRange(b,c-1),window.getSelection().modify("extend","forward","character"))}:function(a,b,c){try{a.setSelectionRange(b,c)}catch(d){}}):(Ma=function(a){try{var b=a.ownerDocument.selection.createRange()}catch(c){return n}if(!b||b.parentElement()!=a)return n;var d=a.value,f=d.length,h=a.createTextRange();h.moveToBookmark(b.getBookmark());var g=a.createTextRange();g.collapse(!1);if(h.compareEndPoints("StartToEnd",
g)>-1)return{start:f,end:f};a=-h.moveStart("character",-f);for(b=d.indexOf("\r");b>-1&&b<a;b=d.indexOf("\r",b+1),a++);if(h.compareEndPoints("EndToEnd",g)>-1)return{start:a,end:f};f=-h.moveEnd("character",-f);for(b=d.indexOf("\r");b>-1&&b<f;b=d.indexOf("\r",b+1),f++);return{start:a,end:f}},P=function(a,b,c){var d=a.createTextRange();d.collapse(!0);for(var f=d.duplicate(),h=0,a=a.value,g=a.indexOf("\n");g>-1&&g<b;g=a.indexOf("\n",g+1))++h;for(d.move("character",b-h);g>-1&&g<c;g=a.indexOf("\n",g+1))++h;
f.move("character",c-h);d.setEndPoint("EndToEnd",f);d.select()});b.P("null",function(){return{L:function(a){a.Oa()}}});b.fa("text/plain","null");return b}();
Nb.P("css",function(b){function c(b,c){A=c;return b}function J(b,o){var t=b.next();if(t=="@")return b.D(/\w/),c("meta",b.ea());else if(t=="/"&&b.w("*"))return o.r=j,j(b,o);else if(t=="<"&&b.w("!"))return o.r=g,g(b,o);else if(t=="=")c(n,"compare");else return(t=="~"||t=="|")&&b.w("=")?c(n,"compare"):t=='"'||t=="'"?(o.r=d(t),o.r(b,o)):t=="#"?(b.D(/\w/),c("atom","hash")):t=="!"?(b.match(/^\s*\w*/),c("keyword","important")):/\d/.test(t)?(b.D(/[\w.%]/),c("number","unit")):/[,.+>*\/]/.test(t)?c(n,"select-op"):
/[;{}:\[\]]/.test(t)?c(n,t):(b.D(/[\w\\\-_]/),c("variable","variable"))}function j(b,d){for(var g=!1,j;(j=b.next())!=n;){if(g&&j=="/"){d.r=J;break}g=j=="*"}return c("comment","comment")}function g(b,d){for(var g=0,j;(j=b.next())!=n;){if(g>=2&&j==">"){d.r=J;break}g=j=="-"?g+1:0}return c("comment","comment")}function d(b){return function(d,g){for(var j=!1,m;(m=d.next())!=n;){if(m==b&&!j)break;j=!j&&m=="\\"}if(!j)g.r=J;return c("string","string")}}var u=b.T,A;return{$:function(b){return{r:J,xa:b||0,
stack:[]}},L:function(b,c){if(b.ga())return n;var d=c.r(b,c),g=c.stack[c.stack.length-1];if(A=="hash"&&g=="rule")d="atom";else if(d=="variable")if(g=="rule")d="number";else if(!g||g=="@media{")d="tag";g=="rule"&&/^[\{\};]$/.test(A)&&c.stack.pop();A=="{"?g=="@media"?c.stack[c.stack.length-1]="@media{":c.stack.push("{"):A=="}"?c.stack.pop():A=="@media"?c.stack.push("@media"):g=="{"&&A!="comment"&&c.stack.push("rule");return d},la:function(b,c){var d=b.stack.length;/^\}/.test(c)&&(d-=b.stack[b.stack.length-
1]=="rule"?2:1);return b.xa+d*u},F:"}"}});Nb.fa("text/css","css");Nb.P("path",function(){return{L:function(b){if(b.ga())return n;if(b.w(/[a-df-z]/i))return"keyword";if(b.match(/[\-+]?(?:[\d\.]e[\-\+]?|[\d\.])+/i))return"number";b.next();return n}}});
(function(){function b(b){return b.substr(0,b.length-1)+"\n"+b.substr(b.length-1)}function c(){E=m.Q();for(var c,d=[];c=fa.exec(E);)d.push(c[1]);if(d.length)E=d.join("\n").replace(pa,b).replace(/^[ \t]+/gm,""),m.Z(E),c=m.V()-1,m.Y({a:0,ch:0},{a:c,ch:m.G(c).length});else for(c=m.Fa(pa);c.Da();){var d=m.G(c.b().a),g=d.substring(c.b().ch,c.c().ch-1);c.replace(g+"\n"+d.substr(c.c().ch-1,1))}C.update();O=setTimeout(J,1)}function J(){try{F=new Ea(E),Z=F.Ja()}catch(b){return}O=setTimeout(j,1)}function j(){for(var b=
(F.W()/1E3*10).toFixed(0)+"s",c=["/* Apply the animation to the target element.                     */\n/* Hardware acceleration requires a nested element for each axis. */","","#target {"],d=0,j=H.length;d<j;d++)c.push("  "+H[d]+"animation: myPathX "+b+" infinite;");c.push("}","","#target > * {");d=0;for(j=H.length;d<j;d++)c.push("  "+H[d]+"animation: myPathY "+b+" infinite;");c.push("}","","#target > * > * {");d=0;for(j=H.length;d<j;d++)c.push("  "+H[d]+"animation: myPathR "+b+" infinite;");c.push("}",
"","/* Define keyframes for each animation axis. */","");d=0;for(j=H.length;d<j;d++){var b=H[d],h=F.Sa(b);c.push("@"+b+"keyframes myPathX {",h.x,"}","@"+b+"keyframes myPathY {",h.y,"}","@"+b+"keyframes myPathR {",h.Ka,"}","")}S=c.join("\n");A.textContent='#target, #target * {-o-animation-name:none;}';O=setTimeout(g,1)}function g(){Q.Z(S);A.textContent=S;y.setAttribute("d","m0,0 "+E);y.parentNode.setAttribute("width",Z.right+10);y.parentNode.setAttribute("height",Z.bottom+10);y.parentNode.parentNode.style.width=Z.right+10+"px";y.parentNode.parentNode.style.height=
Z.bottom+10+"px";G.update();M.update()}var d=document.getElementById("pathEditor"),u=document.getElementById("cssEditor"),A=document.getElementById("previewStyle"),y=document.getElementById("previewPath"),o=document.createElementNS("http://www.w3.org/2000/svg","svg"),t=document.createElementNS("http://www.w3.org/2000/svg","path");o.appendChild(t);t.setAttribute("stroke","currentColor");t.setAttribute("stroke-linecap","round");t.setAttribute("stroke-linejoin","round");t.setAttribute("stroke-width",
"1");t.setAttribute("fill","none");t.setAttribute("id","previewPath");y.parentNode.parentNode.replaceChild(o,y.parentNode);var y=t,Q=Nb(function(b){u.parentNode.replaceChild(b,u)},{value:u.textContent,readOnly:!0,mode:"css"}),m=Nb(function(b){d.parentNode.replaceChild(b,d)},{value:d.textContent,n:function(){clearTimeout(O);O=setTimeout(c,500)},mode:"path"}),H=["-webkit-","-moz-","-ms-","-o-", ""],C=new La(document.getElementById("path")),G=new La(document.getElementById("css")),M=new La(document.getElementById("preview"));
(new lb(document.getElementById("prefix-selector"))).n=function(b){H=b;clearTimeout(O);O=setTimeout(j,500)};(new nb).n=function(c){E=c.replace(pa,b).replace(/^[ \t]+/gm,"");m.Z(E);c=m.V()-1;m.Y({a:0,ch:0},{a:c,ch:m.G(c).length});clearTimeout(O);m.focus();document.getElementById("path").scrollTop=0;document.getElementById("path").scrollLeft=0;C.X.scrollTop=0;C.update();O=setTimeout(J,1)};var E,F,Z,S,O,fa=/\<(?:\w+\:)?(?:animateMotion|path)\s[^\>]*(?:d|path)=["']([^"']*)["'][^>]*\>/ig,pa=/\S[ \t\,]*[a-df-z]/ig;
E=m.Q();J();o=m.V()-1;m.Y({a:0,ch:0},{a:o,ch:m.G(o).length});m.focus();document.getElementById("path").scrollTop=0;document.getElementById("path").scrollLeft=0;C.X.scrollTop=0;C.update()})();